// Comprehensive blog topics database - 500+ topics for SEO domination
export const blogTopics = [
  {
    category: 'APPLICATION_TIPS',
    topics: [
      // Original topics
      'How to Write Compelling ERAS Activity Descriptions',
      'Common ERAS Application Mistakes to Avoid',
      'Maximizing Your 750 Character Limit',
      'How to Choose Your Most Meaningful Experiences',
      'Tips for International Medical Graduates',
      // New topics
      'ERAS Application Checklist: Complete Guide 2025',
      'How to Describe Research Experience in ERAS',
      'Writing About Leadership Roles in Your Application',
      'Explaining Clinical Rotations Effectively',
      'How to Address Red Flags in Your Application',
      'ERAS Hobbies Section: What to Include',
      'Volunteer Experience That Stands Out',
      'How to List Publications in ERAS',
      'Describing Away Rotations in Your Application',
      'ERAS Work Experience Section Guide',
      'How to Highlight Teaching Experience',
      'Writing About Quality Improvement Projects',
      'ERAS Application for Career Changers',
      'How to Show Commitment to Specialty',
      'Describing Observership Experiences',
      'ERAS Application for DO Students',
      'How to List Conference Presentations',
      'Writing About Community Service',
      'ERAS Application Timeline Management',
      'How to Describe Clinical Skills',
      'Addressing Gaps in Education',
      'ERAS Photo Selection Guide',
      'How to List Awards and Honors',
      'Writing About International Experience',
      'ERAS Application for Reapplicants',
    ],
    icon: 'application-tips',
  },
  {
    category: 'PERSONAL_STATEMENT',
    topics: [
      // Original topics
      'Personal Statement Opening Lines That Work',
      'How to Show Not Tell in Your Personal Statement',
      'Connecting Your Story to Your Specialty Choice',
      'Personal Statement Red Flags to Avoid',
      'The Perfect Personal Statement Structure',
      // New topics
      'Personal Statement for Internal Medicine',
      'Surgery Personal Statement Examples',
      'Pediatrics Personal Statement Guide',
      'Emergency Medicine Personal Statement Tips',
      'Psychiatry Personal Statement Strategies',
      'Radiology Personal Statement Essentials',
      'Anesthesiology Personal Statement Writing',
      'Family Medicine Personal Statement Guide',
      'OB/GYN Personal Statement Tips',
      'Pathology Personal Statement Examples',
      'Dermatology Personal Statement Strategies',
      'Neurology Personal Statement Guide',
      'Ophthalmology Personal Statement Tips',
      'Personal Statement Word Count Guide',
      'How to Write About Research Interest',
      'Mentioning Mentors in Personal Statement',
      'Personal Statement Grammar Tips',
      'Using Anecdotes Effectively',
      'Personal Statement Conclusion Strategies',
      'Avoiding Clichés in Personal Statements',
      'Personal Statement Editing Checklist',
      'How to Show Empathy in Writing',
      'Personal Statement for Couples Match',
      'Writing About Patient Interactions',
      'Personal Statement Revision Timeline',
      'How to Stand Out in Competitive Specialties',
      'Personal Statement for IMG Applicants',
      'Addressing Academic Challenges',
      'Personal Statement Brainstorming Techniques',
      'Writing About Career Goals',
    ],
    icon: 'personal-statement',
  },
  {
    category: 'INTERVIEW_PREP',
    topics: [
      // Original topics
      'Virtual Interview Best Practices',
      'Common Residency Interview Questions and Answers',
      'How to Prepare for MMI Interviews',
      'Post-Interview Thank You Notes',
      'Interview Day Etiquette Tips',
      // New topics
      'Behavioral Interview Questions for Residency',
      'How to Answer "Tell Me About Yourself"',
      'Ethical Scenarios in Residency Interviews',
      'Interview Attire Guide for Medical Students',
      'Virtual Interview Technical Setup',
      'How to Research Programs Before Interviews',
      'Questions to Ask During Your Interview',
      'Panel Interview Strategies',
      'One-on-One Interview Tips',
      'How to Handle Stress Questions',
      'Interview Body Language Tips',
      'Discussing Research in Interviews',
      'How to Answer Weakness Questions',
      'Interview Preparation Timeline',
      'Mock Interview Best Practices',
      'How to Stand Out in Virtual Interviews',
      'Addressing Red Flags in Interviews',
      'Interview Follow-Up Strategies',
      'Group Interview Dynamics',
      'Case Presentation in Interviews',
      'How to Discuss Career Goals',
      'Interview Tips for Introverts',
      'Handling Unexpected Questions',
      'Second Look Visit Guide',
      'Interview Scheduling Strategy',
      'How to Show Program Fit',
      'Interview Prep for IMG Students',
      'Discussing Gap Years in Interviews',
      'Interview Confidence Building',
      'How to Handle Multiple Interview Days',
    ],
    icon: 'interview-prep',
  },
  {
    category: 'SPECIALTY_GUIDES',
    topics: [
      // Original topics
      'Matching into Competitive Specialties',
      'Internal Medicine vs Family Medicine',
      'Surgery Residency Application Guide',
      'Pediatrics Application Requirements',
      'Emergency Medicine Match Statistics',
      // New topics - Comprehensive specialty coverage
      'Anesthesiology Residency Complete Guide',
      'Dermatology Match Strategy 2025',
      'Diagnostic Radiology Application Tips',
      'Interventional Radiology Pathway Guide',
      'Neurology Residency Requirements',
      'Neurosurgery Application Strategy',
      'OB/GYN Residency Match Guide',
      'Ophthalmology Match Statistics and Tips',
      'Orthopedic Surgery Application Timeline',
      'Otolaryngology (ENT) Match Guide',
      'Pathology Residency Overview',
      'Physical Medicine & Rehabilitation Guide',
      'Plastic Surgery Match Strategy',
      'Psychiatry Residency Application Tips',
      'Radiation Oncology Match Guide',
      'Urology Residency Requirements',
      'Vascular Surgery Integrated Programs',
      'Cardiology Fellowship Planning',
      'Critical Care Medicine Pathways',
      'Gastroenterology Fellowship Timeline',
      'Hematology/Oncology Career Path',
      'Infectious Disease Fellowship Guide',
      'Nephrology Career Opportunities',
      'Pulmonology Fellowship Planning',
      'Rheumatology Specialty Overview',
      'Sports Medicine Fellowship Options',
      'Choosing Between Academic vs Community',
      'Military Match Process Guide',
      'Osteopathic Students in Allopathic Programs',
      'Combined Programs Overview',
    ],
    icon: 'specialty-guides',
  },
  {
    category: 'TIMELINE_PLANNING',
    topics: [
      // Original topics
      'Month-by-Month ERAS Timeline',
      'When to Take Step 2 CK',
      'Letter of Recommendation Timeline',
      'Away Rotation Planning Guide',
      'ERAS Submission Strategy',
      // New topics
      'M3 Year Planning for Residency',
      'M4 Schedule Optimization Guide',
      'USMLE Timeline for Success',
      'Research Timeline for Competitive Specialties',
      'Sub-Internship Scheduling Strategy',
      'ERAS Opening Day Preparation',
      'Interview Season Calendar Management',
      'Match Week Timeline and Tips',
      'SOAP Week Preparation Timeline',
      'Gap Year Planning Guide',
      'Timeline for IMG Applicants',
      'Early Match Specialties Timeline',
      'Military Match Timeline',
      'Couples Match Planning Timeline',
      'Fellowship Application Timeline',
      'Board Exam Scheduling Strategy',
      'Clinical Rotation Planning',
      'Research Year Timeline',
      'Away Rotation Application Timeline',
      'VSLO Application Strategy',
      'Program Signal Timeline',
      'Supplemental ERAS Timeline',
      'Letter of Intent Timing',
      'Rank List Deadline Planning',
      'Post-Match Timeline',
      'Visa Timeline for International Students',
      'State Licensing Timeline',
      'Moving Timeline for Residents',
      'Orientation Preparation Timeline',
      'First Year Residency Preparation',
    ],
    icon: 'timeline-planning',
  },
  {
    category: 'PROGRAM_SELECTION',
    topics: [
      // Original topics
      'How Many Programs Should You Apply To',
      'Using Program Signals Effectively',
      'Geographic Preferences Strategy',
      'Community vs Academic Programs',
      'Creating Your Program List',
      // New topics
      'Researching Program Culture',
      'Understanding Program Rankings',
      'Fellowship Match Rates by Program',
      'Program Size Considerations',
      'Location Factor in Program Selection',
      'Cost of Living Analysis',
      'Program Curriculum Comparison',
      'Research Opportunities by Program',
      'Teaching Hospital vs County Programs',
      'Programs with International Rotations',
      'Programs Strong in Global Health',
      'LGBTQ+ Friendly Programs',
      'Programs with Strong Mentorship',
      'Work-Life Balance by Program',
      'Moonlighting Opportunities',
      'Programs with Simulation Centers',
      'Rural vs Urban Program Selection',
      'Programs with Strong Alumni Networks',
      'Visa Sponsorship Programs',
      'Programs Accepting DO Students',
      'Caribbean Graduate Friendly Programs',
      'Programs with Research Requirements',
      'Three-Year vs Four-Year Programs',
      'Programs with Unique Tracks',
      'Safety Net Hospital Programs',
      'Programs with Strong Subspecialties',
      'Regional Program Preferences',
      'Programs with Early Clinical Exposure',
      'High Volume vs Low Volume Programs',
      'Programs with International Graduates',
    ],
    icon: 'program-selection',
  },
  {
    category: 'MATCH_STRATEGY',
    topics: [
      // Original topics
      'Understanding the NRMP Algorithm',
      'Couples Match Strategy Guide',
      'SOAP Preparation Tips',
      'Rank List Best Practices',
      'Match Statistics Analysis',
      // New topics
      'Maximizing Your Match Chances',
      'Backup Plan Strategies',
      'Dual Apply Strategy Guide',
      'Ranking Safety Programs',
      'Geographic Clustering Strategy',
      'Program Communication Strategy',
      'Letter of Intent Best Practices',
      'Second Look Visit Decisions',
      'Post-Interview Communication',
      'Thank You Note Templates',
      'Ranking Home Programs',
      'Away Rotation Program Rankings',
      'Understanding Match Violations',
      'Match Week Preparation',
      'SOAP Application Strategy',
      'Unfilled Position Options',
      'Post-SOAP Options',
      'Research Year as Backup',
      'Preliminary Year Strategy',
      'Transitional Year Planning',
      'Advanced Position Matching',
      'Military Match Strategy',
      'Early Match Considerations',
      'San Francisco Match Guide',
      'Ophthalmology Match Strategy',
      'Urology Match Planning',
      'Canadian Match for US Students',
      'US Match for Canadian Students',
      'Reapplication Strategy',
      'Match Statistics by Specialty',
    ],
    icon: 'match-strategy',
  },
  {
    category: 'SUCCESS_STORIES',
    topics: [
      // Original topics
      'From Low Step Scores to Top Program Match',
      'IMG Success Story: Matching into Surgery',
      'Reapplicant Success Strategies',
      'Non-Traditional Path to Residency',
      'Couples Match Success Story',
      // New topics
      'DO Student Matching Orthopedics',
      'Caribbean Graduate in Dermatology',
      'Career Changer Success Story',
      'Military to Civilian Match Success',
      'Single Parent Match Journey',
      'International Student Visa Success',
      'Gap Year to Dream Program',
      'Research Year Success Story',
      'Failed Step Attempts to Match',
      'Community College to Residency',
      'First Generation Doctor Success',
      'Rural Background to Urban Program',
      'Overcoming Mental Health Challenges',
      'Physical Disability Match Success',
      'LGBTQ+ Applicant Journey',
      'Minority in Medicine Success',
      'Women in Surgery Success Story',
      'Older Applicant Match Story',
      'PhD to Clinical Success',
      'Foreign Medical Graduate Journey',
      'SOAP Success Story',
      'Unmatched to Matched Journey',
      'Small School Success Story',
      'No Research to Academic Program',
      'Community Service Focus Success',
      'Athletic Background Advantage',
      'Humanities Major to Medicine',
      'Engineering to Medicine Transition',
      'Business Background Success',
      'Military Veteran Match Story',
    ],
    icon: 'success-stories',
  },
  {
    category: 'USMLE_STRATEGY',
    topics: [
      'Step 1 Study Timeline for Success',
      'Step 2 CK High Yield Topics',
      'Step 2 CS Replacement Guide',
      'Step 3 During Residency Planning',
      'COMLEX to USMLE Conversion',
      'Retaking USMLE Exams Strategy',
      'USMLE Study Resources Comparison',
      'Question Bank Strategy Guide',
      'NBME Practice Exam Analysis',
      'Test Day Strategy and Tips',
      'Score Prediction Accuracy',
      'Dedicated Study Period Planning',
      'Anki for USMLE Success',
      'First Aid Annotation Guide',
      'UWorld Strategy and Tips',
      'Pathoma Integration Guide',
      'Sketchy Medical Review',
      'Board and Beyond Strategy',
      'AMBOSS for Step Exams',
      'Kaplan vs UWorld Comparison',
      'Study Group Effectiveness',
      'Virtual Study Partner Tips',
      'Burnout Prevention During Studying',
      'Exercise and USMLE Performance',
      'Nutrition During Board Prep',
      'Sleep Optimization for Exams',
      'Test Anxiety Management',
      'Score Improvement Strategies',
      'Low Step 1 Score Recovery',
      'High Step 2 CK Achievement',
    ],
    icon: 'usmle-strategy',
  },
  {
    category: 'IMG_RESOURCES',
    topics: [
      'ECFMG Certification Complete Guide',
      'Clinical Experience for IMGs',
      'Observership vs Externship Guide',
      'US Clinical Experience Options',
      'Research Opportunities for IMGs',
      'Networking Strategies for IMGs',
      'IMG-Friendly Program List',
      'Visa Status and Residency',
      'J1 vs H1B Visa Comparison',
      'Green Card During Residency',
      'IMG Timeline for Success',
      'Credential Evaluation Process',
      'US Letter of Recommendation',
      'IMG Personal Statement Tips',
      'Cultural Adjustment Guide',
      'IMG Interview Preparation',
      'Accent Reduction Resources',
      'IMG Match Statistics Analysis',
      'State Licensing for IMGs',
      'IMG Success by Country',
      'Canadian IMGs in US',
      'Indian Medical Graduates Guide',
      'Caribbean Medical School Guide',
      'European Medical Graduates',
      'Middle Eastern Medical Graduates',
      'Asian Medical Graduate Success',
      'African Medical Graduate Guide',
      'Latin American Medical Graduates',
      'IMG Couples Match Strategy',
      'IMG SOAP Success Tips',
    ],
    icon: 'img-resources',
  },
  {
    category: 'RESEARCH_GUIDES',
    topics: [
      'Getting Research in Medical School',
      'Research Year Decision Guide',
      'Publication Strategy for Students',
      'Abstract Submission Guide',
      'Poster Presentation Tips',
      'Oral Presentation Preparation',
      'Research Methodology Basics',
      'IRB Application Process',
      'Clinical vs Basic Science Research',
      'Systematic Review Guide',
      'Case Report Writing Tips',
      'Meta-Analysis for Beginners',
      'Research Funding Sources',
      'Research Mentor Selection',
      'Collaborative Research Tips',
      'International Research Opportunities',
      'Summer Research Programs',
      'Research Electives Guide',
      'Data Analysis for Medical Students',
      'Statistical Software Guide',
      'Research Ethics Overview',
      'Publishing in High Impact Journals',
      'Dealing with Manuscript Rejection',
      'Research Productivity Tips',
      'Balancing Research and Clinical Work',
      'Research in Community Hospitals',
      'Industry-Sponsored Research',
      'NIH Funding for Students',
      'Research Fellowship Applications',
      'Building a Research Portfolio',
    ],
    icon: 'research-guides',
  },
  {
    category: 'WELLNESS_BALANCE',
    topics: [
      'Mental Health During Application Season',
      'Stress Management for Medical Students',
      'Burnout Prevention Strategies',
      'Work-Life Balance in Medicine',
      'Relationship Management During Residency',
      'Financial Wellness for Residents',
      'Exercise Routines for Busy Students',
      'Nutrition on a Medical Student Budget',
      'Sleep Hygiene for Night Shifts',
      'Mindfulness and Meditation Guide',
      'Dealing with Rejection in Medicine',
      'Imposter Syndrome in Medical Training',
      'Building Resilience in Medicine',
      'Support Systems for Medical Students',
      'Time Management Strategies',
      'Study-Life Balance Tips',
      'Vacation Planning During Residency',
      'Hobbies to Maintain During Training',
      'Social Life in Medical School',
      'Dating During Medical Training',
      'Parenting in Medical School',
      'Pet Ownership During Training',
      'Self-Care Strategies',
      'Dealing with Difficult Attendings',
      'Peer Support Groups',
      'Therapy Resources for Students',
      'Substance Use Prevention',
      'Managing Student Loans',
      'Side Hustles for Medical Students',
      'Wellness Resources by Specialty',
    ],
    icon: 'wellness-balance',
  },
  {
    category: 'FINANCIAL_PLANNING',
    topics: [
      'Medical School Loan Management',
      'ERAS Application Budget Guide',
      'Interview Season Costs',
      'Travel Hacking for Interviews',
      'Residency Salary Comparison',
      'Moonlighting Income Guide',
      'Loan Forgiveness Programs',
      'Public Service Loan Forgiveness',
      'Financial Planning for Residents',
      'Disability Insurance for Physicians',
      'Life Insurance Basics',
      'Retirement Planning Early Start',
      'Investment Basics for Medical Students',
      'Credit Card Strategy for Students',
      'Emergency Fund Building',
      'Budgeting Apps for Medical Students',
      'Tax Strategies for Residents',
      'Contract Negotiation Basics',
      'Understanding Malpractice Insurance',
      'Real Estate for Young Physicians',
      'Car Buying Guide for Residents',
      'Wedding Planning on Resident Salary',
      'Having Kids During Training',
      'Scholarship Opportunities',
      'Grant Writing for Students',
      'Financial Aid Maximization',
      'Cost of Living Comparisons',
      'Relocation Expense Management',
      'Banking for Medical Students',
      'Financial Mistakes to Avoid',
    ],
    icon: 'financial-planning',
  },
  {
    category: 'TECHNOLOGY_TOOLS',
    topics: [
      'Best Apps for Medical Students',
      'EHR Training Resources',
      'Telemedicine Skills Development',
      'AI Tools for Medical Education',
      'Digital Note-Taking Strategies',
      'Tablet vs Laptop for Medical School',
      'Medical Calculator Apps',
      'Anatomy Apps Review',
      'Pharmacology App Comparison',
      'Scheduling Apps for Residents',
      'Communication Tools for Teams',
      'Cloud Storage for Medical Students',
      'Password Management Guide',
      'Virtual Reality in Medical Education',
      'Podcast Recommendations',
      'YouTube Channels for Medical Students',
      'Social Media for Professional Development',
      'LinkedIn Optimization for Medical Students',
      'Twitter for Medical Professionals',
      'Online Learning Platforms',
      'Simulation Software Guide',
      'Medical Illustration Tools',
      'Presentation Software Tips',
      'Reference Management Software',
      'Medical Dictionary Apps',
      'Drug Interaction Checkers',
      'Clinical Decision Support Tools',
      'Patient Education Resources',
      'Medical News Aggregators',
      'Productivity Tools for Students',
    ],
    icon: 'technology-tools',
  },
];

// Helper function to get all topics
export function getAllTopics(): string[] {
  return blogTopics.flatMap(category => category.topics);
}

// Helper function to get topics by category
export function getTopicsByCategory(categoryName: string): string[] {
  const category = blogTopics.find(cat => cat.category === categoryName);
  return category ? category.topics : [];
}

// Helper function to get random topic
export function getRandomTopic(): { topic: string; category: string; icon: string } {
  const categoryIndex = Math.floor(Math.random() * blogTopics.length);
  const category = blogTopics[categoryIndex];
  const topicIndex = Math.floor(Math.random() * category.topics.length);
  
  return {
    topic: category.topics[topicIndex],
    category: category.category,
    icon: category.icon,
  };
}

// Track used topics to avoid duplicates
const usedTopics = new Set<string>();

// Get unique random topic
export function getUniqueRandomTopic(): { topic: string; category: string; icon: string } | null {
  const allTopics = getAllTopics();
  const availableTopics = allTopics.filter(topic => !usedTopics.has(topic));
  
  if (availableTopics.length === 0) {
    // Reset if all topics have been used
    usedTopics.clear();
    return getRandomTopic();
  }
  
  // Find a topic that hasn't been used
  let selected = getRandomTopic();
  while (usedTopics.has(selected.topic)) {
    selected = getRandomTopic();
  }
  
  usedTopics.add(selected.topic);
  return selected;
}

// Get topics for specific time of day
export function getTopicForTimeOfDay(hour: number): { topic: string; category: string; icon: string } {
  // Morning (2 AM, 6 AM): Educational guides
  if (hour >= 2 && hour < 10) {
    const educationalCategories = ['SPECIALTY_GUIDES', 'USMLE_STRATEGY', 'RESEARCH_GUIDES', 'FINANCIAL_PLANNING'];
    const category = educationalCategories[Math.floor(Math.random() * educationalCategories.length)];
    const topics = getTopicsByCategory(category);
    const topic = topics[Math.floor(Math.random() * topics.length)];
    const cat = blogTopics.find(c => c.category === category)!;
    return { topic, category, icon: cat.icon };
  }
  
  // Midday (10 AM, 2 PM): Application tips
  if (hour >= 10 && hour < 18) {
    const applicationCategories = ['APPLICATION_TIPS', 'PERSONAL_STATEMENT', 'PROGRAM_SELECTION', 'TIMELINE_PLANNING'];
    const category = applicationCategories[Math.floor(Math.random() * applicationCategories.length)];
    const topics = getTopicsByCategory(category);
    const topic = topics[Math.floor(Math.random() * topics.length)];
    const cat = blogTopics.find(c => c.category === category)!;
    return { topic, category, icon: cat.icon };
  }
  
  // Evening (6 PM, 10 PM): Success stories & interviews
  const eveningCategories = ['SUCCESS_STORIES', 'INTERVIEW_PREP', 'MATCH_STRATEGY', 'WELLNESS_BALANCE'];
  const category = eveningCategories[Math.floor(Math.random() * eveningCategories.length)];
  const topics = getTopicsByCategory(category);
  const topic = topics[Math.floor(Math.random() * topics.length)];
  const cat = blogTopics.find(c => c.category === category)!;
  return { topic, category, icon: cat.icon };
}