export const PRICING_PLANS = [
  {
    id: 'essential',
    name: 'Essential Interview Prep',
    price: 499,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INTERVIEW_ESSENTIAL,
    currency: 'usd',
    interval: 'one-time',
    features: [
      '3 Full-Length Mock Interviews with Detailed Feedback',
      'Comprehensive Preparation Booklet',
      'Virtual Interview Setup & Technical Guide',
      'Common Question Response Framework',
      'Email Support for 30 Days',
    ],
    highlighted: false,
    valueProps: [
      'Build confidence with realistic mock interviews',
      'Master the most common interview questions',
      'Perfect for first-time applicants',
    ],
  },
  {
    id: 'professional',
    name: 'Professional Interview Mastery',
    price: 1000,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INTERVIEW_PROFESSIONAL,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Everything in Essential Package',
      '6 Full-Length Mock Interviews with Expert Coaching',
      'Advanced Preparation Booklet by Ex-Program Directors',
      '2 One-on-One Strategy Sessions (45 min each)',
      'Personalized Weakness Analysis & Improvement Plan',
      'Behavioral Question Deep-Dive Sessions',
      'Program-Specific Research & Talking Points',
      'Priority Email & Phone Support for 60 Days',
    ],
    highlighted: true,
    badge: 'Most Popular',
    valueProps: [
      'Work directly with ex-program directors',
      'Identify and eliminate your specific weaknesses',
      'Practice until you can confidently answer any question',
      'Students average 3.2x more interview callbacks',
    ],
  },
  {
    id: 'elite',
    name: 'Elite Interview Concierge',
    price: 1399,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INTERVIEW_ELITE,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Everything in Professional Package',
      '10 Full-Length Mock Interviews with Video Analysis',
      'Premium Preparation Booklet + Competitive Program Guide',
      '4 One-on-One Strategy Sessions (60 min each)',
      'Dedicated Ex-Program Director Mentor',
      'Program-by-Program Customized Preparation',
      'Post-Interview Debrief Calls (within 24 hours)',
      'Application Red Flags Review & Mitigation Strategy',
      'Real-Time Interview Prep (Day-Before Sessions)',
      'Body Language & Communication Coaching',
      'Direct Phone/Text Access to Your Mentor',
      '100% Money-Back Guarantee if No Interview Improvement',
    ],
    highlighted: false,
    badge: 'Best Value',
    valueProps: [
      'White-glove service for competitive specialties',
      'Your own ex-program director on speed dial',
      'Perfect for IMGs, reapplicants, and competitive specialties',
      'Students average 5.8 interview callbacks vs. 2.1 national average',
      'Comprehensive support from prep to match day',
    ],
  },
];

// Keep INTERVIEW_PREP_PACKAGES for backwards compatibility (now same as PRICING_PLANS)
export const INTERVIEW_PREP_PACKAGES = PRICING_PLANS;

export const ADDONS = [
  {
    id: 'additional-mock-interview',
    name: 'Additional Mock Interview',
    price: 150,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ADDITIONAL_MOCK,
    description: 'Add one more full-length mock interview with personalized feedback',
  },
  {
    id: 'rush-prep',
    name: 'Rush Preparation',
    price: 199,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_RUSH,
    description: 'Expedited mock interview scheduling within 24-48 hours',
  },
  {
    id: 'specialty-focus',
    name: 'Specialty-Specific Focus Session',
    price: 129,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_SPECIALTY,
    description: 'Deep dive into specialty-specific questions and expectations (1 hour)',
  },
];
