export const PRICING_PLANS = [
  {
    id: 'basic',
    name: 'Basic Package',
    price: 149,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_BASIC,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Personal Statement Review',
      'CV/Resume Formatting',
      '1 Round of Revisions',
      '48-hour Turnaround',
      'Basic Grammar Check',
    ],
    highlighted: false,
  },
  {
    id: 'professional',
    name: 'Professional Package',
    price: 299,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PROFESSIONAL,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Everything in Basic',
      'Activity Descriptions Review',
      'Letter of Recommendation Guidance',
      '3 Rounds of Revisions',
      '24-hour Turnaround',
      'Advanced Content Optimization',
      'Interview Preparation Guide',
    ],
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    id: 'premium',
    name: 'Premium Package',
    price: 499,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PREMIUM,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Everything in Professional',
      'Complete Application Review',
      'School-Specific Tailoring',
      'Unlimited Revisions for 30 days',
      '12-hour Turnaround',
      'Priority Support',
      '1-on-1 Strategy Session (30 min)',
      'Mock Interview Session',
    ],
    highlighted: false,
  },
];

export const INTERVIEW_PREP_PACKAGES = [
  {
    id: 'interview-essential',
    name: 'Essential Interview Prep',
    price: 500,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INTERVIEW_ESSENTIAL,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Comprehensive Preparation Booklet by Ex-Program Directors',
      '2 Full-Length Mock Interviews with Detailed Feedback',
      'Specialty-Specific Question Bank (200+ Questions)',
      'Virtual Interview Setup & Technical Guide',
      'Common Question Response Framework',
      'Post-Interview Thank You Note Templates',
      'Email Support for 30 Days',
    ],
    highlighted: false,
    valueProps: [
      'Curated by physicians who served on residency selection committees',
      'Proven strategies that helped 500+ applicants match',
      'Practice the exact questions asked in real interviews',
    ],
  },
  {
    id: 'interview-professional',
    name: 'Professional Interview Mastery',
    price: 1000,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INTERVIEW_PROFESSIONAL,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Everything in Essential Package',
      '5 Full-Length Mock Interviews with Expert Coaching',
      'Personalized Weakness Analysis & Improvement Plan',
      'MMI (Multiple Mini Interview) Format Practice',
      'Behavioral Question Deep-Dive Sessions',
      'Program-Specific Research & Talking Points',
      '3 One-on-One Strategy Sessions (45 min each)',
      'Video Recording & Playback Analysis',
      'Body Language & Communication Coaching',
      'Priority Email & Phone Support for 60 Days',
    ],
    highlighted: true,
    badge: 'Most Popular',
    valueProps: [
      'Work directly with ex-program directors who interview candidates',
      'Identify and eliminate your specific weaknesses',
      'Practice until you can confidently answer any question',
      'Average students receive 3.2x more match offers',
    ],
  },
  {
    id: 'interview-elite',
    name: 'Elite Interview Concierge',
    price: 1500,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INTERVIEW_ELITE,
    currency: 'usd',
    interval: 'one-time',
    features: [
      'Everything in Professional Package',
      'Unlimited Mock Interviews for 60 Days',
      'Dedicated Ex-Program Director Mentor',
      'Program-by-Program Customized Preparation',
      'Post-Interview Debrief Calls (within 24 hours)',
      'Application Red Flags Review & Mitigation Strategy',
      'Competitive Program Interview Intensive',
      'Real-Time Interview Prep (Day-Before Sessions)',
      'Thank You Note Personalization Service',
      'Direct Phone/Text Access to Your Mentor',
      'Guest Lecture Access: Inside the Selection Committee',
      '100% Money-Back Guarantee if No Interview Improvement',
    ],
    highlighted: false,
    badge: 'Best Value',
    valueProps: [
      'White-glove service for competitive specialties',
      'Your own ex-program director on speed dial',
      'The only package with unlimited practice',
      'Perfect for IMGs, reapplicants, and competitive specialties',
      'Students average 5.8 interview invites vs. 2.1 national average',
    ],
  },
];

export const ADDONS = [
  {
    id: 'rush',
    name: 'Rush Delivery',
    price: 99,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_RUSH,
    description: '6-hour turnaround for urgent applications',
  },
  {
    id: 'additional-school',
    name: 'Additional School Application',
    price: 79,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ADDITIONAL_SCHOOL,
    description: 'Tailor your application for one additional school',
  },
  {
    id: 'additional-mock-interview',
    name: 'Additional Mock Interview',
    price: 150,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ADDITIONAL_MOCK,
    description: 'Add one more full-length mock interview with feedback',
  },
];